import { Client, Walk } from '../types';

const addr = (line1: string, line2: string, city: string, state: string, postal: string) => ({
  line1,
  line2,
  city,
  state,
  postal,
});

export const clients: Client[] = [
  {
    id: 'c1',
    name: 'Sarah Johnson',
    address: addr('1420 Pine St', '', 'Seattle', 'WA', '98122'),
    phone: '(206) 555-0101',
    pricePerWalk: 25,
    keyLocation: 'Under the blue flowerpot',
    dogs: [
      {
        id: 'd1',
        name: 'Max',
        breed: 'Golden Retriever',
        age: 3,
        weight: 65,
        emoji: '🐕',
        traits: [
          { label: 'Friendly', type: 'positive' },
          { label: 'Good on leash', type: 'positive' },
          { label: 'Pulls', type: 'warning' },
        ],
        vet: 'Dr. Smith',
        vetPhone: '(206) 555-0190',
        medical: 'Allergic to chicken treats',
      },
    ],
  },
  {
    id: 'c2',
    name: 'Mike Chen',
    address: addr('820 Oak Ave', '', 'Seattle', 'WA', '98104'),
    phone: '(206) 555-0202',
    pricePerWalk: 30,
    keyLocation: 'Key box by the garage, code 1234',
    dogs: [
      {
        id: 'd2',
        name: 'Luna',
        breed: 'Border Collie',
        age: 2,
        weight: 42,
        emoji: '🦮',
        traits: [
          { label: 'Very active', type: 'positive' },
          { label: 'Needs exercise', type: 'warning' },
        ],
        vet: 'Dr. Lee',
        vetPhone: '(206) 555-0220',
        medical: 'None',
      },
    ],
  },
  {
    id: 'c3',
    name: 'Anna Davis',
    address: addr('305 Maple Dr', '', 'Seattle', 'WA', '98109'),
    phone: '(206) 555-0303',
    pricePerWalk: 35,
    keyLocation: 'Door code: 5678',
    dogs: [
      {
        id: 'd3',
        name: 'Bella',
        breed: 'Poodle',
        age: 4,
        weight: 18,
        emoji: '🐩',
        traits: [{ label: 'Friendly', type: 'positive' }],
        vet: 'Dr. Park',
        vetPhone: '(206) 555-0330',
        medical: 'None',
      },
      {
        id: 'd4',
        name: 'Charlie',
        breed: 'Beagle',
        age: 5,
        weight: 25,
        emoji: '🐕‍🦺',
        traits: [
          { label: 'Friendly', type: 'positive' },
          { label: 'Loud', type: 'warning' },
        ],
        vet: 'Dr. Park',
        vetPhone: '(206) 555-0330',
        medical: 'None',
      },
    ],
  },
  {
    id: 'c4',
    name: 'Tom Williams',
    address: addr('750 Cedar St', '', 'Seattle', 'WA', '98121'),
    phone: '(206) 555-0404',
    pricePerWalk: 25,
    keyLocation: 'Hidden under the mat',
    dogs: [
      {
        id: 'd5',
        name: 'Rocky',
        breed: 'Labrador',
        age: 6,
        weight: 70,
        emoji: '🐶',
        traits: [
          { label: 'Calm', type: 'positive' },
          { label: 'Good on leash', type: 'positive' },
        ],
        vet: 'Dr. Johnson',
        vetPhone: '(206) 555-0440',
        medical: 'Hip dysplasia — no long walks',
      },
    ],
  },
];

export const walks: Walk[] = [
  {
    id: 'w1',
    clientId: 'c1',
    dogIds: ['d1'],
    scheduledAt: new Date().toISOString().split('T')[0] + 'T10:00:00',
    durationMinutes: 30,
    status: 'scheduled',
    paymentStatus: 'unpaid',
  },
  {
    id: 'w2',
    clientId: 'c2',
    dogIds: ['d2'],
    scheduledAt: new Date().toISOString().split('T')[0] + 'T13:00:00',
    durationMinutes: 45,
    status: 'scheduled',
    paymentStatus: 'unpaid',
  },
  {
    id: 'w3',
    clientId: 'c3',
    dogIds: ['d3', 'd4'],
    scheduledAt: new Date().toISOString().split('T')[0] + 'T15:30:00',
    durationMinutes: 30,
    status: 'done',
    paymentStatus: 'unpaid',
    actualDurationMinutes: 32,
  },
  {
    id: 'w4',
    clientId: 'c1',
    dogIds: ['d1'],
    scheduledAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + 'T10:00:00',
    durationMinutes: 30,
    status: 'done',
    paymentStatus: 'unpaid',
    actualDurationMinutes: 32,
  },
  {
    id: 'w5',
    clientId: 'c4',
    dogIds: ['d5'],
    scheduledAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + 'T11:00:00',
    durationMinutes: 30,
    status: 'done',
    paymentStatus: 'unpaid',
    actualDurationMinutes: 28,
  },
  {
    id: 'w6',
    clientId: 'c4',
    dogIds: ['d5'],
    scheduledAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] + 'T11:00:00',
    durationMinutes: 30,
    status: 'done',
    paymentStatus: 'unpaid',
    actualDurationMinutes: 30,
  },
];
