import { StyleSheet } from "react-native";
import type { ThemeColors } from "../../theme";
import { PAYMENTS_MIN_TOUCH } from "./paymentsConstants";

export function createPaymentsSectionsStyles(colors: ThemeColors) {
  return StyleSheet.create({
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  summaryCard: {
    width: "48.85%",
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryCardAccent: {
    backgroundColor: colors.greenDeep,
    borderColor: colors.greenBorder,
  },
  summaryCardAccentLabel: {
    color: "rgba(255,255,255,0.58)",
  },
  summaryCardAccentMeta: {
    color: "rgba(255,255,255,0.45)",
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: colors.textMuted,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 22,
    fontWeight: "500",
    color: colors.text,
    letterSpacing: -0.5,
  },
  summaryValueGreen: {
    color: colors.greenText,
  },
  summaryValueAmber: {
    color: colors.amberDefault,
  },
  summaryMeta: {
    marginTop: 2,
    fontSize: 12,
    color: colors.textMuted,
  },
  chartSection: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 14,
    overflow: "hidden",
  },
  chartBody: {
    position: "relative",
    overflow: "hidden",
  },
  proTag: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(245,158,11,0.16)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(245,158,11,0.3)",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  proTagText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.amberDefault,
  },
  chartBars: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 6,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
    height: 70,
  },
  barWrap: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  bar: {
    width: "100%",
    minHeight: 4,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    backgroundColor: colors.surfaceHigh,
  },
  barActive: {
    backgroundColor: colors.greenDefault,
  },
  barLabel: {
    fontSize: 11,
    color: colors.textMuted,
  },
  barLabelActive: {
    color: colors.greenDefault,
  },
  chartFoot: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 12,
    fontSize: 12,
    color: colors.textMuted,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.05)",
  },
  chartFootAccent: {
    color: colors.greenDefault,
    fontWeight: "500",
  },
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 2,
    paddingBottom: 8,
  },
  sectionRowPaid: {
    marginTop: 2,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    color: colors.textMuted,
  },
  unpaidSectionTotal: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.amberDefault,
    textTransform: "none",
    letterSpacing: 0,
  },
  sectionMeta: {
    fontSize: 12,
    color: colors.textMuted,
  },
  emptyCard: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.text,
  },
  emptyText: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
  },
  clientCard: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    overflow: "hidden",
  },
  clientHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 14,
    minHeight: PAYMENTS_MIN_TOUCH + 8,
    backgroundColor: colors.surfaceHigh,
  },
  clientLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  clientAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.greenDeep,
    alignItems: "center",
    justifyContent: "center",
  },
  clientAvatarText: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.greenText,
  },
  clientName: {
    fontSize: 15,
    fontWeight: "500",
    color: colors.text,
  },
  clientSub: {
    marginTop: 1,
    fontSize: 13,
    color: colors.textMuted,
  },
  clientRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  clientAmount: {
    fontSize: 17,
    fontWeight: "500",
    color: colors.amberDefault,
  },
  chevronOpen: {
    transform: [{ rotate: "180deg" }],
  },
  walksList: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  markAllButton: {
    marginHorizontal: 12,
    marginTop: 10,
    marginBottom: 8,
    backgroundColor: colors.greenDeep,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(91,175,114,0.25)",
    borderRadius: 12,
    paddingVertical: 15,
    minHeight: PAYMENTS_MIN_TOUCH + 6,
    alignItems: "center",
    justifyContent: "center",
  },
  markAllButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.greenText,
  },
  walkCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    minHeight: PAYMENTS_MIN_TOUCH + 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  dateCol: {
    width: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  dateDay: {
    fontSize: 17,
    lineHeight: 18,
    fontWeight: "500",
    color: colors.text,
  },
  dateMon: {
    marginTop: 1,
    fontSize: 10,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  vLine: {
    width: StyleSheet.hairlineWidth,
    height: 34,
    backgroundColor: "rgba(255,255,255,0.07)",
  },
  walkInfo: {
    flex: 1,
    minWidth: 0,
  },
  walkDog: {
    fontSize: 15,
    fontWeight: "500",
    color: colors.text,
  },
  walkMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 3,
  },
  walkMetaText: {
    fontSize: 12,
    color: colors.textMuted,
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#333330",
  },
  walkRight: {
    alignItems: "flex-end",
    gap: 6,
  },
  walkPrice: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.text,
  },
  walkPricePaid: {
    color: colors.greenDefault,
  },
  markButton: {
    backgroundColor: colors.surfaceHigh,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minHeight: PAYMENTS_MIN_TOUCH,
    minWidth: PAYMENTS_MIN_TOUCH + 36,
    justifyContent: "center",
    alignItems: "center",
  },
  markButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  unpaidClientCard: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 8,
    overflow: "hidden",
  },
  unpaidClientHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  unpaidClientHeaderCollapsed: {
    borderBottomWidth: 0,
  },
  unpaidClientLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  unpaidClientAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  unpaidClientAvatarAmber: {
    backgroundColor: "rgba(186,117,23,0.18)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(186,117,23,0.3)",
  },
  unpaidClientAvatarTeal: {
    backgroundColor: "rgba(29,158,117,0.15)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(29,158,117,0.25)",
  },
  unpaidClientAvatarText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
  },
  unpaidClientName: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.text,
    marginBottom: 2,
  },
  unpaidClientSub: {
    fontSize: 13,
    color: "rgba(255,255,255,0.28)",
  },
  unpaidClientRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginLeft: 8,
  },
  unpaidClientAmount: {
    minWidth: 40,
    textAlign: "right",
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: -0.4,
    color: colors.amberDefault,
  },
  unpaidClientBody: {
    overflow: "hidden",
  },
  unpaidWalkList: {
    paddingTop: 4,
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  unpaidWalkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 12,
  },
  unpaidWalkBadge: {
    minWidth: 40,
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.055)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.11)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  unpaidWalkBadgeDay: {
    fontSize: 15,
    lineHeight: 15,
    fontWeight: "600",
    color: colors.text,
  },
  unpaidWalkBadgeMon: {
    fontSize: 8,
    fontWeight: "500",
    color: "rgba(255,255,255,0.28)",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  unpaidWalkInfo: {
    flex: 1,
    minWidth: 0,
  },
  unpaidWalkTop: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    marginBottom: 3,
  },
  unpaidWalkName: {
    fontSize: 15,
    fontWeight: "500",
    color: colors.text,
  },
  unpaidWalkDog: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    color: "rgba(255,255,255,0.28)",
  },
  unpaidWalkMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  unpaidWalkTime: {
    fontSize: 12,
    color: "rgba(255,255,255,0.28)",
  },
  unpaidWalkDuration: {
    fontSize: 12,
    color: "rgba(255,255,255,0.18)",
  },
  unpaidWalkRight: {
    alignItems: "flex-end",
    gap: 6,
    flexShrink: 0,
  },
  unpaidWalkAmount: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.text,
    letterSpacing: -0.3,
  },
  unpaidMarkPaidButton: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    minHeight: PAYMENTS_MIN_TOUCH,
    justifyContent: "center",
    backgroundColor: colors.greenSubtle,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(74,184,74,0.22)",
  },
  unpaidMarkPaidButtonText: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.greenText,
  },
  unpaidWalkSeparator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    marginHorizontal: 8,
  },
  paidHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 14,
    minHeight: PAYMENTS_MIN_TOUCH + 8,
    backgroundColor: colors.surfaceHigh,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  paidSectionCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 8,
    overflow: "hidden",
  },
  paidMonthCard: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 16,
  },
  paidMonthName: {
    fontSize: 13,
    fontWeight: "500",
    color: "rgba(255,255,255,0.28)",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  paidMonthAmount: {
    fontSize: 32,
    lineHeight: 32,
    fontWeight: "600",
    color: colors.greenDefault,
    letterSpacing: -1,
  },
  paidMonthStats: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
  },
  paidMonthStatPill: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.11)",
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  paidMonthStatText: {
    fontSize: 13,
    color: "rgba(255,255,255,0.28)",
    fontWeight: "400",
  },
  paidLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
  },
  paidSub: {
    marginTop: 1,
    fontSize: 12,
    color: colors.textMuted,
  },
  paidClientRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  paidClientText: {
    fontSize: 11,
    color: colors.textMuted,
  },
  paidTotal: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.greenDefault,
  },
  emptyPaidBody: {
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  paidBadge: {
    maxWidth: "100%",
  },
  paidPaymentCard: {
    backgroundColor: colors.surface,
    overflow: "hidden",
    marginHorizontal: 12,
    marginTop: 10,
  },
  paidCardsDivider: {
    marginHorizontal: 12,
    marginTop: 10,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
  },
  paidDayGroup: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 8,
    overflow: "hidden",
  },
  paidDayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  paidDayHeaderCollapsed: {
    borderBottomWidth: 0,
  },
  paidDayLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  paidDayDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.greenDefault,
    opacity: 0.5,
  },
  paidDayLabel: {
    fontSize: 13,
    fontWeight: "500",
    color: "rgba(255,255,255,0.55)",
    letterSpacing: 0.3,
  },
  paidDayRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginLeft: 10,
  },
  paidShowAllAction: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.greenText,
  },
  paidDaySum: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(74,184,74,0.7)",
    letterSpacing: -0.3,
  },
  paidDayCountPill: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 5,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  paidDayCountText: {
    fontSize: 11,
    color: "rgba(255,255,255,0.28)",
  },
  paidDayChevronOpen: {
    transform: [{ rotate: "90deg" }],
  },
  paidDayWalks: {
    paddingTop: 4,
    paddingHorizontal: 10,
    paddingBottom: 6,
  },
  paidWalkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 12,
  },
  paidWalkSeparator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    marginHorizontal: 8,
  },
  paidWalkBadge: {
    minWidth: 38,
    width: 38,
    height: 38,
    backgroundColor: "rgba(255,255,255,0.055)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.11)",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  paidWalkBadgeNum: {
    fontSize: 15,
    lineHeight: 15,
    fontWeight: "600",
    color: colors.text,
  },
  paidWalkBadgeMon: {
    fontSize: 8,
    fontWeight: "500",
    color: "rgba(255,255,255,0.28)",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  paidWalkInfo: {
    flex: 1,
    minWidth: 0,
  },
  paidWalkTop: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    marginBottom: 3,
  },
  paidWalkClient: {
    fontSize: 15,
    fontWeight: "500",
    color: colors.text,
  },
  paidWalkDog: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    color: "rgba(255,255,255,0.28)",
  },
  paidWalkBottom: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  paidWalkTime: {
    fontSize: 12,
    color: "rgba(255,255,255,0.28)",
  },
  paidWalkDuration: {
    fontSize: 12,
    color: "rgba(255,255,255,0.18)",
  },
  paidWalkStatusPill: {
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 2,
    backgroundColor: "rgba(74,184,74,0.11)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(74,184,74,0.22)",
  },
  paidWalkStatusText: {
    fontSize: 11,
    fontWeight: "500",
    color: colors.greenText,
  },
  paidWalkAmount: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.greenDefault,
    letterSpacing: -0.4,
    flexShrink: 0,
  },
  paidShowAllFooter: {
    marginHorizontal: 8,
    marginTop: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  paidShowAllFooterText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  paidDateGroupHeader: {
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  paidDateGroupLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
    color: colors.textMuted,
    letterSpacing: 0.3,
  },
  paidDateGroupAction: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.greenText,
  },
  paidCardHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  paidCardMonth: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
  },
  paidCardMeta: {
    marginTop: 2,
    fontSize: 11,
    color: "rgba(255,255,255,0.38)",
  },
  paidCardAmount: {
    fontSize: 17,
    fontWeight: "600",
    color: colors.greenDefault,
    letterSpacing: -0.2,
  },
  paidCardBody: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  paidPanel: {
    flex: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  paidPanelClient: {
    backgroundColor: "rgba(91,128,255,0.12)",
  },
  paidPanelDog: {
    backgroundColor: "rgba(29,158,117,0.12)",
  },
  paidPanelLabel: {
    fontSize: 10,
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  paidPanelLabelClient: {
    color: "#a99df5",
  },
  paidPanelLabelDog: {
    color: "#34d399",
  },
  paidPanelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  paidPanelAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  paidPanelAvatarClient: {
    backgroundColor: "rgba(124,111,212,0.3)",
  },
  paidPanelAvatarDog: {
    backgroundColor: "rgba(29,158,117,0.3)",
  },
  paidPanelDogEmoji: {
    fontSize: 14,
    lineHeight: 16,
  },
  paidPanelTextCol: {
    flex: 1,
    minWidth: 0,
  },
  paidPanelName: {
    fontSize: 12,
    fontWeight: "500",
  },
  paidPanelNameClient: {
    color: "#e8e4fb",
  },
  paidPanelNameDog: {
    color: "#d1fae5",
  },
  paidPanelSub: {
    marginTop: 1,
    fontSize: 10,
  },
  paidPanelSubClient: {
    color: "#a99df5",
  },
  paidPanelSubDog: {
    color: "#34d399",
  },
  paidCardFooter: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  paidFooterMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
  },
  paidMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  paidMetaText: {
    fontSize: 11,
    color: "rgba(255,255,255,0.4)",
  },
  paidCardBadge: {
    minHeight: 30,
  },
  paymentWalkCard: {
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  paymentWalkMainRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 14,
    padding: 16,
  },
  paymentWalkDateBlock: {
    minWidth: 52,
    paddingHorizontal: 8,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    backgroundColor: "#2a2a2d",
  },
  paymentWalkDateDay: {
    fontSize: 26,
    lineHeight: 26,
    fontWeight: "600",
    letterSpacing: -0.8,
    color: colors.text,
  },
  paymentWalkDateMonth: {
    fontSize: 10,
    fontWeight: "500",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.38)",
  },
  paymentWalkDetailCol: {
    flex: 1,
    gap: 10,
    justifyContent: "space-between",
    minWidth: 0,
  },
  paymentWalkClientRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  paymentWalkClientInfo: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  paymentWalkPeopleRow: {
    gap: 5,
  },
  paymentWalkPersonLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    minWidth: 0,
  },
  paymentWalkPersonIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#2a2a2d",
    alignItems: "center",
    justifyContent: "center",
  },
  paymentWalkDogEmoji: {
    fontSize: 12,
    lineHeight: 14,
  },
  paymentWalkPersonLabel: {
    fontSize: 12,
    minWidth: 34,
    color: "rgba(255,255,255,0.35)",
  },
  paymentWalkPersonName: {
    flex: 1,
    fontSize: 15,
    fontWeight: "500",
    color: colors.text,
  },
  paymentWalkPersonSub: {
    fontSize: 13,
    fontWeight: "400",
    color: "rgba(255,255,255,0.38)",
  },
  paymentWalkMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.07)",
  },
  paymentWalkMetaGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
    minWidth: 0,
  },
  paymentWalkMetaText: {
    fontSize: 13,
    color: "rgba(255,255,255,0.3)",
  },
  paymentWalkAmount: {
    fontSize: 22,
    fontWeight: "600",
    letterSpacing: -0.7,
    color: colors.text,
    flexShrink: 0,
  },
  paymentWalkAmountPaid: {
    color: colors.greenText,
  },
  paymentWalkFooter: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.06)",
    alignItems: "flex-end",
  },
  paymentWalkPaidBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "rgba(52,211,153,0.12)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(52,211,153,0.22)",
    maxWidth: "100%",
    flexShrink: 1,
  },
  paymentWalkPaidBadgeText: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.greenText,
  },
  paymentWalkActionButton: {
    minHeight: PAYMENTS_MIN_TOUCH,
    minWidth: PAYMENTS_MIN_TOUCH + 22,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.greenDeep,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.greenBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  paymentWalkActionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.greenText,
  },
  insightsHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  insightsCard: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 24,
    overflow: "hidden",
    position: "relative",
  },
  insightRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  insightLabel: {
    fontSize: 14,
    color: colors.textMuted,
  },
  insightValue: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
  },
  unlockButton: {
    marginHorizontal: 12,
    marginTop: 10,
    marginBottom: 12,
    backgroundColor: colors.greenDeep,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(91,175,114,0.25)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    minHeight: PAYMENTS_MIN_TOUCH + 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  unlockButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.greenText,
  },
  });
}

export type PaymentsSectionsStyles = ReturnType<typeof createPaymentsSectionsStyles>;
