import { StyleSheet } from "react-native";
import { radius } from "../../theme";
import type { ThemeColors } from "../../theme";

export function createDogDetailScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  loader: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bg,
  },

  hero: {
    backgroundColor: colors.greenDeep,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  editBtn: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.18)",
    paddingVertical: 5,
    paddingHorizontal: 16,
    borderRadius: 999,
  },
  editBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.45)",
  },
  dogRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  dogCircle: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  dogName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: -0.3,
    marginBottom: 2,
    lineHeight: 18,
  },
  dogBreed: {
    fontSize: 12,
    color: "rgba(255,255,255,0.4)",
    marginBottom: 7,
  },
  metaRow: { flexDirection: "row", gap: 5 },
  metaPill: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 5,
    paddingVertical: 2,
    paddingHorizontal: 7,
  },
  metaPillText: {
    fontSize: 10,
    color: "rgba(255,255,255,0.5)",
  },
  traitRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 12 },
  trait: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  traitText: { fontSize: 12, fontWeight: "500" },

  tabs: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  tab: {
    flex: 1,
    paddingTop: 14,
    paddingBottom: 12,
    alignItems: "center",
    justifyContent: "flex-start",
    position: "relative",
  },
  tabText: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.textMuted,
  },
  tabTextActive: { color: colors.text },
  tabUnderline: {
    position: "absolute",
    bottom: 0,
    alignSelf: "center",
    width: 28,
    height: 2.5,
    backgroundColor: colors.greenDefault,
    borderRadius: 2,
  },

  page: { flex: 1, minHeight: 0 },
  pageScroll: { flex: 1, backgroundColor: colors.bg },
  pageContent: { paddingBottom: 32 },

  secTitle: {
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
    color: colors.textMuted,
    marginBottom: 10,
    paddingHorizontal: 20,
    marginTop: 18,
  },

  alertCard: {
    marginHorizontal: 20,
    marginBottom: 4,
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderTopRightRadius: radius.sm,
    borderBottomRightRadius: radius.sm,
    borderBottomLeftRadius: radius.sm,
    borderLeftWidth: 3,
    borderLeftColor: colors.amberDefault,
    backgroundColor: colors.amberSubtle,
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  alertDanger: {
    borderLeftColor: colors.redDefault,
    backgroundColor: colors.redSubtle,
    marginHorizontal: 20,
    marginBottom: 4,
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderTopRightRadius: radius.sm,
    borderBottomRightRadius: radius.sm,
    borderBottomLeftRadius: radius.sm,
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  alertIcon: { fontSize: 16, marginTop: 1 },
  alertTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.amberText,
    marginBottom: 4,
  },
  alertBody: {
    fontSize: 13,
    color: colors.amberText,
    lineHeight: 20,
  },
  alertTitleDanger: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.redText,
    marginBottom: 4,
  },
  alertBodyDanger: {
    fontSize: 13,
    color: "#A32D2D",
    lineHeight: 20,
  },

  infoCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    marginHorizontal: 20,
    overflow: "hidden",
    marginBottom: 4,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  ik: { fontSize: 14, color: colors.textMuted },
  iv: {
    fontSize: 14,
    color: colors.text,
    fontWeight: "500",
    textAlign: "right",
    flex: 1,
    marginLeft: 12,
  },
  ivLink: {
    fontSize: 14,
    color: "#8BD09C",
    fontWeight: "500",
    textAlign: "right",
    flex: 1,
    marginLeft: 12,
  },

  vetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  vetIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.greenSubtle,
    alignItems: "center",
    justifyContent: "center",
  },
  vetName: { fontSize: 15, fontWeight: "600", color: colors.text },
  vetMeta: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  callBtn: {
    marginLeft: "auto",
    backgroundColor: colors.greenSubtle,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 999,
  },
  callBtnText: { fontSize: 13, fontWeight: "600", color: colors.text },

  walkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 13,
    paddingHorizontal: 16,
  },
  walkRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  walkDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  walkDate: { fontSize: 14, color: colors.text, fontWeight: "500", flex: 1 },
  walkDur: { fontSize: 13, color: colors.textMuted },
  walkAmt: {
    fontSize: 14,
    fontWeight: "600",
    minWidth: 36,
    textAlign: "right",
  },

  loadMore: {
    alignItems: "center",
    paddingTop: 14,
    paddingBottom: 4,
  },
  loadMoreText: {
    fontSize: 13,
    color: colors.greenDefault,
    fontWeight: "500",
  },
  dangerZoneLabelPad: {
    paddingHorizontal: 20,
  },
  dangerZoneButtonPad: {
    marginHorizontal: 20,
  },
  });
}
